# Generated by Django 5.0.3 on 2024-03-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'user',
                'managed': (False,),
            },
        ),
    ]
