# Generated by Django 5.0.3 on 2024-03-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModels',
            new_name='User_Models',
        ),
        migrations.AlterModelTable(
            name='user_models',
            table='users',
        ),
    ]
