# Generated by Django 5.0.3 on 2024-03-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_models_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Models',
        ),
    ]
