# Generated by Django 5.0.3 on 2024-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
