# Generated by Django 5.0.3 on 2024-03-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_products_alter_userdetails_birthday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='product',
        ),
    ]
