# Generated by Django 5.0.3 on 2024-03-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_price_alter_product_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_path',
            new_name='image',
        ),
    ]
