# Generated by Django 5.0.3 on 2024-04-19 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cart_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('cart_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cart')),
            ],
        ),
    ]
