# Generated by Django 5.0.3 on 2024-04-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart_item_id',
            field=models.IntegerField(),
        ),
    ]
