# Generated by Django 5.0.3 on 2024-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_orders_cart_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='contact',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_name',
            field=models.CharField(default=5, max_length=250),
            preserve_default=False,
        ),
    ]
