# Generated by Django 5.0.3 on 2024-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cart_address_cart_contact_cart_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(default=5),
        ),
        migrations.AddField(
            model_name='orders',
            name='contact',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
