# Generated by Django 5.0.3 on 2024-04-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_cart_address_remove_cart_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
