# Generated by Django 5.0.3 on 2024-04-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomOrder',
            new_name='CustomOrders',
        ),
    ]
